// Project27/frontend/src/App.jsx
import React from 'react';
import { Routes, Route } from 'react-router-dom';
import { Layout as AntLayout, Menu, Typography } from 'antd';
import {
  GiftOutlined,
  ClockCircleOutlined,
  HistoryOutlined,
  BarChartOutlined,
  UserOutlined
} from '@ant-design/icons';
import { useState } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import Dashboard from './pages/Dashboard';
import GiftList from './pages/GiftList';
import Reminders from './pages/Reminders';
import History from './pages/History';
import './App.css';

const { Header, Content, Sider } = AntLayout;
const { Title } = Typography;

function App() {
  const navigate = useNavigate();
  const location = useLocation();
  const [collapsed, setCollapsed] = useState(false);

  const menuItems = [
    {
      key: '/',
      icon: <BarChartOutlined />,
      label: '数据概览',
    },
    {
      key: '/gifts',
      icon: <GiftOutlined />,
      label: '礼品清单',
    },
    {
      key: '/reminders',
      icon: <ClockCircleOutlined />,
      label: '送礼提醒',
    },
    {
      key: '/history',
      icon: <HistoryOutlined />,
      label: '历史记录',
    },
  ];

  const handleMenuClick = ({ key }) => {
    navigate(key);
  };

  return (
    <AntLayout style={{ minHeight: '100vh' }}>
      <Sider collapsible collapsed={collapsed} onCollapse={setCollapsed}>
        <div style={{ height: 64, display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'white' }}>
          {!collapsed && <Title level={4} style={{ color: 'white', margin: 0 }}>🎁 礼品管理</Title>}
          {collapsed && <GiftOutlined style={{ fontSize: 24 }} />}
        </div>
        <Menu
          theme="dark"
          selectedKeys={[location.pathname]}
          mode="inline"
          items={menuItems}
          onClick={handleMenuClick}
        />
      </Sider>
      <AntLayout>
        <Header style={{ background: '#fff', padding: '0 24px', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <Title level={3} style={{ margin: 0 }}>节日礼品清单管理系统</Title>
          <UserOutlined style={{ fontSize: 20 }} />
        </Header>
        <Content style={{ margin: '24px', background: '#fff', padding: 24, borderRadius: 8 }}>
          <Routes>
            <Route path="/" element={<Dashboard />} />
            <Route path="/gifts" element={<GiftList />} />
            <Route path="/reminders" element={<Reminders />} />
            <Route path="/history" element={<History />} />
          </Routes>
        </Content>
      </AntLayout>
    </AntLayout>
  );
}

export default App;

// Project53/frontend/src/App.vue
<template>
  <a-layout style="min-height: 100vh">
    <a-layout-sider v-model:collapsed="collapsed" collapsible theme="dark">
      <div class="logo">
        <span v-if="!collapsed">酒水管理系统</span>
        <span v-else>酒</span>
      </div>
      <a-menu theme="dark" mode="inline" :selected-keys="selectedKeys">
        <a-menu-item key="/" @click="goTo('/')">
          <template #icon><dashboard-outlined /></template>
          <span>首页概览</span>
        </a-menu-item>
        <a-menu-item key="/category" @click="goTo('/category')">
          <template #icon><appstore-outlined /></template>
          <span>酒水品类</span>
        </a-menu-item>
        <a-menu-item key="/product" @click="goTo('/product')">
          <template #icon><stock-outlined /></template>
          <span>酒水库存</span>
        </a-menu-item>
        <a-menu-item key="/sale" @click="goTo('/sale')">
          <template #icon><shopping-cart-outlined /></template>
          <span>售卖记录</span>
        </a-menu-item>
        <a-menu-item key="/expiry-alert" @click="goTo('/expiry-alert')">
          <template #icon><warning-outlined /></template>
          <span>临期提醒</span>
        </a-menu-item>
      </a-menu>
    </a-layout-sider>
    <a-layout>
      <a-layout-header style="background: #fff; padding: 0 24px">
        <span class="header-title">{{ currentTitle }}</span>
      </a-layout-header>
      <a-layout-content style="margin: 16px">
        <router-view />
      </a-layout-content>
    </a-layout>
  </a-layout>
</template>

<script setup>
import { ref, computed } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import {
  DashboardOutlined,
  AppstoreOutlined,
  StockOutlined,
  ShoppingCartOutlined,
  WarningOutlined
} from '@ant-design/icons-vue'

const collapsed = ref(false)
const router = useRouter()
const route = useRoute()

const selectedKeys = computed(() => [route.path])
const currentTitle = computed(() => route.meta.title || '酒水管理系统')

const goTo = (path) => {
  router.push(path)
}
</script>

<style>
.logo {
  height: 60px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #fff;
  font-size: 18px;
  font-weight: bold;
  background: #001529;
}
.header-title {
  font-size: 18px;
  font-weight: 600;
}
</style>
